### PR TITLE
Use fuse3 compatible appimagetool

### PR DESCRIPTION
**Pull request by Samueru-sama**
This fixes a common issue with distros that are shipping libfuse3 instead of libfuse2. 

Note: `$VERSION` can be anything, just that it is a requirement of this appimagetool. If for any reason the CI fails to get the version from the application itself (as sometimes that happens with some graphical applications when there is no available display server) you can just assign version to a dummy value and that is it.

### CODE REVIEW

**Comment by Samueru-sama** [comment]
Btw when I tested the appimage in Artix linux I got this error (the one that's available for download): 

`qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""`

I noticed you have `--exclude-library="libxcb*"` in the script. So maybe that's the issue?

**Comment by sandboxgamedev123** [comment]
Hi Samueru-sama,

Thank you for your comments.

Regarding the "qt.qpa.plugin" error, it is possible that excluding "libxcb" might have caused or contributed to the error. The AppImage was built for Linux Mint and it worked for different versions of Linux Mint.

I plan on changing from Qt to SDL so that might not be an issue with SDL.

Regarding the changes to "makeappimage_64-bit.sh", what is the "api.github.com" website? Is this officially part of GitHub? If so, is there any documentation you can share regarding this?

**Comment by sandboxgamedev123** [comment]
Hi Samueru-sama,

Thank you for your comments.

Regarding the "qt.qpa.plugin" error, I think it is possible that excluding "libxcb" might have caused or contributed to the error. The AppImage was built for Linux Mint and it worked for different versions of Linux Mint.

I plan on changing from Qt to SDL so that might not be an issue with SDL.

Regarding the changes to "makeappimage_64-bit.sh", what is the "api.github.com" website? Is this officially part of GitHub? If so, is there any documentation you can share regarding this?

**Comment by Samueru-sama** [comment]
> Hi Samueru-sama,
> 
> Thank you for your comments.
> 
> Regarding the "qt.qpa.plugin" error, I think it is possible that excluding "libxcb" might have caused or contributed to the error. The AppImage was built for Linux Mint and it worked for different versions of Linux Mint.
> 
> I plan on changing from Qt to SDL so that might not be an issue with SDL.

There is somebody that already made an SDL build, this might be useful as reference: https://github.com/mantralunar/mantralunar.github.io/blob/main/scripts/ppsspp.sh

> Regarding the changes to "makeappimage_64-bit.sh", what is the "api.github.com" website? Is this officially part of GitHub? If so, is there any documentation you can share regarding this?

https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28

And the appimagetool being used is this one: https://github.com/probonopd/go-appimage, Cemu builds their appimage with that appimagetool, as ubuntu and forks no longer ship with libfuse2 by default.

**Comment by sandboxgamedev123** [comment]
> There is somebody that already made an SDL build, this might be useful as reference: https://github.com/mantralunar/mantralunar.github.io/blob/main/scripts/ppsspp.sh
 
I appreciate providing additional information regarding an SDL build, but my progress on it already went well.

The other scripts from that repository might be helpful for other projects.

> https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28
> 
> And the appimagetool being used is this one: https://github.com/probonopd/go-appimage, Cemu builds their appimage with that appimagetool, as ubuntu and forks no longer ship with libfuse2 by default.

Thank you for the link and the information.

Would an AppImage built with libfuse3 be compatible with distros that have libfuse2?

**Comment by Samueru-sama** [comment]
> Would an AppImage built with the "appimagetool" for "libfuse3" compatibility also be compatible with distros that have "libfuse2"?

Yes.

**Comment by sandboxgamedev123** [comment]
This seems good. I made a 32-bit AppImage and a 64-bit AppImage based on your recommended "appimagetool". The 32-bit version and the 64-bit version seem to work well on different versions of Linux Mint.

It seems like you did a very good job.

I recommend making a pull request for the main PPSSPP repository with the changes you made. I could do it for you if you would like me to but it might be more appropriate if you made the pull request since it would be based on your changes. I can support your pull request and include a changed script for making a 32-bit AppImage.

**Comment by Samueru-sama** [comment]
I already made my fork of ppsspp, you may want to pr the `i686` changes to it before I open the one to ppsspp.

**Comment by sandboxgamedev123** [comment]
Okay, I made a pull request for your fork of PPSSPP.

**Comment by Samueru-sama** [comment]
> Okay, I made a pull request for your fork of PPSSPP.

Done opening the PR at ppsspp as well. 

If you need help with the CI to build the appimage let me know, you can use the CI of the appimages that I make as reference.

**Comment by sandboxgamedev123** [comment]
Okay. Also, I made a release for a 32-bit AppImage and a 64-bit AppImage using the changed "appimagetool". Feel free to download either version if you would like to.

**Comment by Samueru-sama** [comment]
> Okay. Also, I made a release for a 32-bit AppImage and a 64-bit AppImage using the changed "appimagetool".

Works perfect, no more missing library errors: 

image

**Comment by Samueru-sama** [comment]
Vulkan also works btw 👍

**Comment by sandboxgamedev123** [comment]
That was nice to read. It seemed to work well for you.

**Comment by Samueru-sama** [comment]
Hey is everything ok? I noticed some of your comments disappeared here and from ppsspp 🤔

**Comment by sandboxgamedev123** [comment]
Hi,

This repository will be closed.

**Pull request merged**
